name: ClearPlugin
author: laurdotgg
version: '${project.version}'
main: me.itskronx11.clearplugin.ClearPlugin
api-version: '1.20'
folia-supported: true
commands:
  clear:
    permission: 'clearplugin.use'
    usage: 'Usage: /clear <user> <item> <amount>'